/**
 * Main layout shell with dark gradient background
 */

import type { ReactNode } from 'react';
import { Nav } from './Nav';

export interface LayoutShellProps {
  children: ReactNode;
}

const navItems = [
  { id: 'hero', label: 'Summary' },
  { id: 'commands', label: 'Commands' },
  { id: 'activity', label: 'Activity' },
  { id: 'categories', label: 'Categories' },
  { id: 'highlights', label: 'Highlights' },
];

export function LayoutShell({ children }: LayoutShellProps) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-black text-slate-50">
      <Nav items={navItems} />
      <main className="max-w-5xl mx-auto px-4 pt-20 pb-16">
        {children}
      </main>
      <footer className="text-center py-8 text-slate-500 text-sm">
        Generated by Terminal Wrapped
      </footer>
    </div>
  );
}
